test-warnings: true
doc-warnings: false
member-warnings: false

ignore-paths:
  - docs

autodetect: true

pylint:
  disable:
    - missing-module-docstring
    - missing-class-docstring
    - missing-function-docstring
    - invalid-name
    - too-few-public-methods
    - too-many-instance-attributes
    - too-many-arguments
    - too-many-branches
    - too-many-locals
    - too-many-statements
    - line-too-long
    - redefined-outer-name
    - django-not-available
  options:
    max-line-length: 160
    max-args: 6
