#!/usr/bin/env bash

# make bash behave
set -euox pipefail
IFS=$'\n\t'

# constants
stdout=1
stderr=2
success=0
badusage=64

while read -r line; do
  IFS=',' read -r script repo_or_pkg qual <<< "$line"

  since=$(psql -qXtAc "SELECT COALESCE((SELECT max(date + 1) FROM download_stats WHERE ${qual}), '2016-01-01'::date);")

  stats_csv=$(mktemp)
  ${script} ${repo_or_pkg} ${since} | psql -qXtAc 'COPY download_stats FROM STDIN WITH (FORMAT csv, HEADER true)'
done <<DATA_SOURCES
packagecloud_downloads,community,name='citus' AND release IS NOT NULL
packagecloud_downloads,enterprise,name='citus-enterprise' AND release IS NOT NULL
github_clones,citus,os IS NULL
homebrew_downloads,citus,os='macOS'
DATA_SOURCES
