#!/usr/bin/env bash

# make bash behave
set -euox pipefail
IFS=$'\n\t'

# constants
stdout=1
stderr=2
success=0
badusage=64

if [ -e ~/.dashboard_secrets ]; then
  source ~/.dashboard_secrets
fi

while read -r line; do
  IFS=',' read -r script repo_or_pkg table qual <<< "$line"

  since=$(psql -qXtAc "SELECT COALESCE((SELECT max(date + 1) FROM ${table} WHERE ${qual}), '2016-01-01'::date);" "${DATABASE_URL}")

  ${script} ${repo_or_pkg} ${since} | psql -qXtAc "COPY ${table} FROM STDIN WITH (FORMAT csv, HEADER true)" "${DATABASE_URL}"
done <<DATA_SOURCES
packagecloud_downloads,community,download_stats,name='citus' AND release IS NOT NULL
packagecloud_downloads,enterprise,download_stats,name='citus-enterprise' AND release IS NOT NULL
github_clones,citus,download_stats,os IS NULL
homebrew_downloads,citus,download_stats,os='macOS'
docker_pulls,citus,download_levels,name='citus' AND os='Docker'
rubygem_installs,activerecord-multi-tenant,download_levels,name='activerecord-multi-tenant' AND os='ruby'
DATA_SOURCES
