#!/bin/bash

set -euo pipefail

REPORT_EMAIL=${REPORT_EMAIL:-burak@citusdata.com metin@citusdata.com furkan@citusdata.com}
POSTGRES_GITREF=${POSTGRES_GITREF:-REL_11_STABLE}
CITUS_GITREF=${CITUS_GITREF:-master}

echo "ENV:"
echo "     REPORT_EMAIL:" $REPORT_EMAIL
echo "  POSTGRES_GITREF:" $POSTGRES_GITREF
echo "     CITUS_GITREF:" $CITUS_GITREF

read -p "Press enter to continue"

# create a key pair just for valgrind tests and store it in valgrind-test.pem
echo "Creating key pair..."
key_name=valgrind_$RANDOM
aws ec2 create-key-pair --key-name $key_name --query 'KeyMaterial' --output text > $key_name.pem
chmod 600 $key_name.pem

# start an instance with ami-f4cc1de2 image(i.e. Ubuntu Xenial 16.04)
echo "Starting an instance..."
valgrind_instance_id=$(aws ec2 run-instances \
    --image-id ami-f4cc1de2 \
    --count 1 \
    --instance-type r3.2xlarge \
    --key-name $key_name \
    --instance-initiated-shutdown-behavior terminate \
    --user-data file://download-test-scripts \
    --query 'Instances[0].InstanceId' \
    --output text)
echo "  instance id:" $valgrind_instance_id

# tag the instance as ValgrindTest
echo "Tagging the instance..."
aws ec2 create-tags \
    --resources "${valgrind_instance_id}" \
    --tags Key=Name,Value=ValgrindTest

# wait for instance creation complete
echo "Waiting for completion of instance creation... (This may take a several minutes)"
aws ec2 wait instance-status-ok \
    --instance-id "${valgrind_instance_id}"

# get the instance ip address
echo "Getting the ip address of the instance..."
valgrind_instance_ip=$(aws ec2 describe-instances \
    --instance-ids "${valgrind_instance_id}" \
    --query 'Reservations[0].Instances[0].PublicIpAddress' \
    --output text)

# run valgrind tests
echo "Running the valgrind tests..."
echo "This will take hours, test results will be sent via e-mail."
ssh -o StrictHostKeyChecking=no -i $key_name.pem ubuntu@$valgrind_instance_ip 'REPORT_EMAIL="${REPORT_EMAIL}" POSTGRES_GITREF="${POSTGRES_GITREF}" CITUS_GITREF="${CITUS_GITREF}" srceen -d -m run-valgrind-tests'

echo login:
echo "  " ssh -o StrictHostKeyChecking=no -i $key_name.pem ubuntu@$valgrind_instance_ip
echo

#delete the key pair after we are done with tests
echo "please run when done"
echo "  " aws ec2 delete-key-pair --key-name $key_name
echo