#!/bin/bash

set -euo pipefail

# create a key pair just for valgrind tests and store it in valgrind-test.pem
echo "Creating key pair..."
key_name=valgrind_$RANDOM
aws ec2 create-key-pair --key-name $key_name --query 'KeyMaterial' --output text > $key_name.pem
chmod 600 $key_name.pem

# start an instance with ami-f4cc1de2 image(i.e. Ubuntu Xenial 16.04)
echo "Starting an instance..."
valgrind_instance_id=$(aws ec2 run-instances \
    --image-id ami-f4cc1de2 \
    --count 1 \
    --instance-type r3.2xlarge \
    --key-name $key_name \
    --instance-initiated-shutdown-behavior terminate \
    --user-data file://download-test-scripts \
    --query 'Instances[0].InstanceId' \
    --output text)
echo "  instance id:" $valgrind_instance_id

# tag the instance as ValgrindTest
echo "Tagging the instance..."
aws ec2 create-tags \
    --resources "${valgrind_instance_id}" \
    --tags Key=Name,Value=ValgrindTest

# wait for instance creation complete
echo "Waiting for completion of instance creation... (This may take a several minutes)"
aws ec2 wait instance-status-ok \
    --instance-id "${valgrind_instance_id}"

# get the instance ip address
echo "Getting the ip address of the instance..."
valgrind_instance_ip=$(aws ec2 describe-instances \
    --instance-ids "${valgrind_instance_id}" \
    --query 'Reservations[0].Instances[0].PublicIpAddress' \
    --output text)

# put the script to be run for installation and tests 
scp \
    -o IdentitiesOnly=yes \
    -o StrictHostKeyChecking=no \
    -i $key_name.pem \
    run-valgrind-tests ubuntu@$valgrind_instance_ip:~/

echo "Go to your instance with below ssh command and run ~/run-valgrind-tests in a detachable session..."
echo "You are required to enter github credentials to fetch enterprise repository"

echo login:
echo "  " ssh -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -i $key_name.pem ubuntu@$valgrind_instance_ip
echo

aws ec2 delete-key-pair --key-name $key_name

