#!/bin/bash

set -euo pipefail

CITUS_GITREF=${CITUS_GITREF:-enterprise-master}
POSTGRES_GITREF=${POSTGRES_GITREF:-REL_12_STABLE}

# download and install required packages
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq \
    build-essential \
    libreadline6 \
    libreadline6-dev \
    zlib1g-dev \
    flex \
    bison \
    libssl-dev \
    valgrind \
    mailutils \
    uuid-dev \ # for propagate-extension-commands.sql regression test 
    libcurl4-openssl-dev

# set environment variables
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export PATH=$HOME/pgsql/bin:$PATH

# download and install PostgreSQL
rm -rf postgresql/
git clone -b "${POSTGRES_GITREF}" --depth 1 git://git.postgresql.org/git/postgresql.git
cd postgresql/
./configure \
    --prefix=$HOME/pgsql \
    --with-openssl \
    --enable-cassert \
    --enable-debug \
    --with-uuid=e2fs \
    CFLAGS="-ggdb -Og -DUSE_VALGRIND"

# we will use this to parallelize PostgreSQL compilation
procs="$(nproc)"
mjobs="$((procs + 1))"

# install postgresql
make install -j "${mjobs}" -s

# install contrib extensions
cd contrib/
make clean
make -j "${mjobs}" -s
sudo make install

# download and install citus-enterprise master
cd ~
rm -rf citus-enterprise/
git clone -b "${CITUS_GITREF}" --depth 2 https://github.com/citusdata/citus-enterprise.git
cd citus-enterprise/
./configure
make clean
make install -j "${mjobs}" -s

# run valgrind tests
cd src/test/regress
make check-multi-vg VALGRIND_LOG_FILE=logs.txt || true
