#!/bin/bash

set -euo pipefail

REPORT_EMAIL=${REPORT_EMAIL:-burak@citusdata.com metin@citusdata.com furkan@citusdata.com}
CITUS_GITREF=${CITUS_GITREF:-master}
POSTGRES_GITREF=${POSTGRES_GITREF:-REL_11_STABLE}

echo "ENV:"
echo "     REPORT_EMAIL:" $REPORT_EMAIL
echo "  POSTGRES_GITREF:" $POSTGRES_GITREF
echo "     CITUS_GITREF:" $CITUS_GITREF

ulimit -c unlimited

# download and install required packages
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get install -yq \
    build-essential \
    libreadline6 \
    libreadline6-dev \
    zlib1g-dev \
    flex \
    bison \
    libssl-dev \
    valgrind \
    mailutils \
    libcurl4-openssl-dev

# set environment variables
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export PATH=$HOME/pgsql/bin:$PATH

# download and install PostgreSQL
git clone -b "${POSTGRES_GITREF}" --depth 1 git://git.postgresql.org/git/postgresql.git
cd postgresql/
./configure \
    --prefix=$HOME/pgsql \
    --with-openssl \
    --enable-cassert \
    --enable-debug \
    CFLAGS="-ggdb -Og -DUSE_VALGRIND"

# we will use this to parallelize PostgreSQL compilation
procs="$(nproc)"
mjobs="$((procs + 1))"
make install -j "${mjobs}" -s

# download and install Citus
cd ..
git clone -b "${CITUS_GITREF}" --depth 1 https://github.com/citusdata/citus.git
cd citus/
./configure
make clean
make install -j "${mjobs}" -s

# run valgrind tests
cd src/test/regress
make check-multi-vg VALGRIND_LOG_FILE=logs.txt || true

attachments=""
if [ -s logs.txt ]; then
    attachments=$attachments" -A logs.txt"
fi

if [ -s regression.diffs ]; then
    attachments=$attachments" -A regression.diffs"
fi

if [ -z "$attachments" ]; then
    mail -aFrom:valgrind-test@citusdata.com -s "[Valgrind Test Results] - Success" $REPORT_EMAIL < /dev/null
else
    mail -aFrom:valgrind-test@citusdata.com -s "[Valgrind Test Results] - Failure" $attachments $REPORT_EMAIL < /dev/null
fi

# just to ensure everything is completed in the test instance
sleep 30

# shut-down the instance, this will also terminate the instance because we set instance-initiated-shutdown-behavior to terminate
sudo shutdown -h now
