#!/bin/bash

# make bash behave
set -euo pipefail
IFS=$'\n\t'

# constants
stderr=2
badusage=64

pkgflavor="${TRAVIS_BRANCH%%-*}"
pkgauth="${PACKAGECLOUD_API_TOKEN}:"

# populate variables from packaging metadata file
# shellcheck source=/dev/null
source pkgvars

# set default values for certain packaging variables
declare pkglatest # to make shellcheck happy
hubproj="${hubproj:-${pkgname}}"
nightlyref="${nightlyref:-master}"
releasepg="${releasepg:-9.5,9.6}"
nightlypg="${nightlypg:-${releasepg}}"
latestpg=$(echo "${releasepg}" | tr ',' '\n' | sort -t. -k1,1n -k2,2n | tail -n1)
versioning="${versioning:-simple}"

case "${pkgflavor}" in
    debian)
        pkgflavor='deb'
        pkgfull="postgresql-${latestpg}-${pkgname}"

        # add minor/major version to package name if using fancy versioning
        if [ "${versioning}" == 'fancy' ]; then
            suffix=$(echo "${pkglatest}" | grep -oE '^[0-9]+\.[0-9]+')
            pkgfull="postgresql-${latestpg}-${pkgname}-${suffix}"
        fi

        pkgarch="amd64"
        jqfilter='map(.version + "-" + .release)'
        ;;
    redhat)
        pkgflavor='rpm'

        # add minor/major version to package name if using fancy versioning
        if [ "${versioning}" == 'fancy' ]; then
            infix=$(echo "${pkglatest}" | grep -oE '^[0-9]+\.[0-9]+' | tr -d '.')
            pkgfull="${pkgname}${infix}_${latestpg//./}"
        else
            pkgfull="${pkgname}_${latestpg//./}"
        fi

        pkgarch="x86_64"
        jqfilter='map(.version + "-" + .release | gsub("\\.centos$";"") | gsub("\\.[^.]*$";""))'
        ;;
    *)
        echo "$0: unknown package flavor -- ${pkgflavor}" >&2
        usage $stderr $badusage
        ;;
esac

pkgapiurl="https://packagecloud.io/api/v1/repos/citusdata/${PKG_REPOTYPE}"
pkgapiurl+="/package/${pkgflavor}/${TARGET_PLATFORM}/${pkgfull}/${pkgarch}/versions.json"

needrelease=$(curl -sf -u "${pkgauth}" "${pkgapiurl}?per_page=1000" | \
              jq -r "${jqfilter} | index(\"${pkglatest}\") < 0")

if [ "${needrelease}" == "true" ]; then
    citus_package -p "${TARGET_PLATFORM}" 'local' release
    mkdir -p pkgs/releases
    shopt -s nullglob
    mv ./*/*.rpm ./*/*.deb pkgs/releases
    git clean -df -e pkgs
else
    echo 'release up to date'
fi
