#!/bin/bash

# make bash behave
set -euo pipefail
IFS=$'\n\t'

# constants
stderr=2
badusage=64

latestpg="9.5"
pkgflavor="${TRAVIS_BRANCH%%-*}"
pkgauth="${PACKAGECLOUD_API_TOKEN}:"
hubauth="Authorization: token ${GITHUB_TOKEN}"

# populate variables from packaging metadata file
# shellcheck source=/dev/null
source pkgvars

# set default values for certain packaging variables
hubproj="${hubproj:-${pkgname}}"
nightlyref="${nightlyref:-master}"
releasepg="${releasepg:-9.5,9.6}"
nightlypg="${nightlypg:-${releasepg}}"
latestpg=$(echo "${nightlypg}" | tr ',' '\n' | sort -t. -k1,1n -k2,2n | tail -n1)

case "${pkgflavor}" in
    debian)
        pkgflavor='deb'
        pkgfull="postgresql-${latestpg}-${pkgname}"
        pkgarch="amd64"
        ;;
    redhat)
        pkgflavor='rpm'
        pkgfull="${pkgname}_${latestpg//./}"
        pkgarch="x86_64"
        ;;
    *)
        echo "$0: unknown package flavor -- ${pkgflavor}" >&2
        usage $stderr $badusage
        ;;
esac

pkgapiurl="https://packagecloud.io/api/v1/repos/citusdata/${PKG_REPOTYPE}-nightlies"
pkgapiurl+="/package/${pkgflavor}/${TARGET_PLATFORM}/${pkgfull}/${pkgarch}/versions.json"

response=$(curl -w '\n%{http_code}\n' -s -u "${pkgauth}" "${pkgapiurl}?per_page=1000")

httpcode=$(echo "${response}" | tail -n1)
case "${httpcode}" in
    404)
        httpbody='[]'
        ;;
    200)
        httpbody=$(echo "${response}" | sed '$d')
        ;;
    *)
        echo "$0: bad response code from packagecloud -- ${httpcode}" >&2
        exit $noservice
        ;;
esac

epochstr='"1970-01-01T00:00:00.000Z"'
lastnightly=$(echo "${httpbody}" | jq -r "map(.created_at) | sort | last // ${epochstr}")

hubapiurl="https://api.github.com/repos/citusdata/${hubproj}/commits?"
hubapiurl+="sha=${nightlyref}&since=${lastnightly}&per_page=1"

newcommitcount=$(curl -sf -H "${hubauth}" "${hubapiurl}" | jq -r 'length')

if [ "${newcommitcount}" -gt 0 ]; then
    citus_package -p "${TARGET_PLATFORM}" 'local' nightly
    mkdir -p pkgs/nightlies
    shopt -s nullglob
    mv ./*/*.rpm ./*/*.deb pkgs/nightlies
    git clean -df -e pkgs
else
    echo 'nightly up to date'
fi
