#!/bin/bash

set -eux

# exit early if a custom build is not needed
if [ -z "${USE_CUSTOM_PG}" ]; then
  exit
fi

# clone PostgreSQL
cd ~
git clone -b "REL${PGVERSION//./_}_STABLE" --depth 1 git://git.postgresql.org/git/postgresql.git

# we will use this to parallelize PostgreSQL compilation
procs="$(nproc)"
mjobs="$((procs + 1))"

# configure, build and install PostgreSQL
cd postgresql
./configure --enable-cassert --enable-debug --with-openssl \
    --mandir="/usr/share/postgresql/${PGVERSION}/man" \
    --docdir="/usr/share/doc/postgresql-doc-${PGVERSION}" \
    --sysconfdir=/etc/postgresql-common \
    --datarootdir=/usr/share/ \
    --datadir="/usr/share/postgresql/${PGVERSION}" \
    --bindir="/usr/lib/postgresql/${PGVERSION}/bin" \
    --libdir=/usr/lib/x86_64-linux-gnu/ \
    --libexecdir=/usr/lib/postgresql/ \
    --includedir=/usr/include/postgresql/ \

make -j "${mjobs}" -s all
make -j "${mjobs}" -s -C src/test/isolation
sudo make install

# install postgresql-common to get psql wrappers, etc.
sudo apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install postgresql-common
