#!/bin/bash

# Inspired by https://gist.github.com/petere/6023944

set -eux

# exit early if a custom build is needed
if [ -n "${USE_CUSTOM_PG:-}" ]; then
    exit
fi

# always install postgresql-common
packages="postgresql-common postgresql-contrib-$PGVERSION libedit-dev libpam0g-dev libselinux1-dev"

packages="$packages postgresql-$PGVERSION postgresql-server-dev-$PGVERSION"

# shellcheck disable=SC2086
sudo apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install $packages
