#!/bin/bash

# Inspired by https://gist.github.com/petere/6023944

set -eux

# stop all existing instances (because of https://github.com/travis-ci/travis-cookbooks/pull/221)
sudo service postgresql stop

# remove existing installation of postgresql
if [ -z "${USE_CUSTOM_PG:-}" ]; then
    sudo apt-get --purge -y remove postgresql-*
fi

# and make sure they don't come back
echo 'exit 0' | sudo tee /etc/init.d/postgresql
sudo chmod a+x /etc/init.d/postgresql
