#!/bin/bash

set -eux

noinput=66

if [ "$#" -eq 0 ]; then
    echo "$0: you must specify test targets" >&2
    exit $noinput
fi

status=0
testtargets="$*"

# Configure, build, and install extension
./configure --enable-coverage PG_CONFIG="/usr/lib/postgresql/${PGVERSION}/bin/pg_config"
make all
sudo make install

# Change to test directory for remainder
cd src/test/regress

# Run tests. DBs owned by non-standard owner put socket in /tmp
# shellcheck disable=SC2086
make ${testtargets} || status=$?

# Print diff if it exists
if test -f regression.diffs; then cat regression.diffs; fi

exit $status
