#!/bin/bash

# Inspired by https://gist.github.com/petere/6023944

set -eux

# import the PostgreSQL repository key
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -

# wtf, Google?
sudo rm -f /etc/apt/sources.list.d/google-chrome*
sudo rm -f /etc/apt/sources.list.d/pgdg.list

# add the PostgreSQL repository
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" >> /etc/apt/sources.list.d/postgresql.list'

# need testing repository after version 14
if [ "${PGVERSION%%.*}" -gt "14" ]; then
    # add a PostgreSQL testing repository
    echo "Adding test repository"
    # Used tee because of this check: https://github.com/koalaman/shellcheck/wiki/SC2024
    echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg-testing main ${PGVERSION}" | sudo tee -a /etc/apt/sources.list.d/postgresql.list > /dev/null
#    echo "Package: *\nPin: release n=$(lsb_release -cs)-pgdg-testing\nPin-Priority: 600" | sudo tee -a /etc/apt/preferences.d/postgresql.pref > /dev/null
fi
echo "List installed repositories"
sudo grep -rhE ^deb /etc/apt/sources.list*
echo "-------"

# update package index files from sources
sudo apt-get update -qq

# remove traces of PostgreSQL versions
# see: postgresql.org/message-id/20130508192711.GA9243@msgid.df7cb.de
sudo update-alternatives --remove-all postmaster.1.gz
