#!/bin/bash

# Inspired by https://gist.github.com/petere/6023944

set -eux

# import the PostgreSQL repository key
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys ACCC4CF8

# wtf, Google?
sudo rm -f /etc/apt/sources.list.d/google-chrome*

# add the PostgreSQL 9.5 and 10 repositories
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main 10" >> /etc/apt/sources.list.d/postgresql.list'

# need testing repository after version 10
if [ "${PGVERSION%%.*}" -gt '10' ]; then
    # add a PostgreSQL testing repository
    sudo sh -Ec 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg-testing main ${PGVERSION}" >> /etc/apt/sources.list.d/postgresql.list'

    sudo sh -c 'echo "Package: *\nPin: release n=$(lsb_release -cs)-pgdg-testing\nPin-Priority: 600" >> /etc/apt/preferences.d/postgresql.pref'
fi

# update package index files from sources
sudo apt-get update -qq

# remove traces of PostgreSQL versions
# see: postgresql.org/message-id/20130508192711.GA9243@msgid.df7cb.de
sudo update-alternatives --remove-all postmaster.1.gz
