name: Citus package all platforms tests

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  PACKAGING_PASSPHRASE: ${{ secrets.PACKAGING_PASSPHRASE }}
  MICROSOFT_EMAIL: gindibay@microsoft.com
  USER_NAME: Gurkan Indibay
  MAIN_BRANCH: all-citus
  PACKAGE_CLOUD_API_TOKEN: ${{ secrets.PACKAGE_CLOUD_API_TOKEN }}

on:
  push:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  unit_test_execution:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          [
            el/7,
            el/8,
            ol/7,
            debian/stretch,
            debian/buster,
            ubuntu/xenial,
            ubuntu/bionic,
            ubuntu/focal,
          ]
    env:
      PLATFORM: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev libssl-dev python3-testresources

      - name: Define git credentails
        run: git config --global user.email "${MICROSOFT_EMAIL}"&& git config --global user.name "${USER_NAME}"

      - name: Install python requirements
        run: python -m pip install -r packaging_automation/requirements.txt

      - name: Citus package tests
        run: python -m pytest -q packaging_automation/tests/test_citus_package.py
