name: Citus package tests

on:
  push:
    branches:
      - "**"

  workflow_dispatch:
    inputs:
      prj_ver:
        description: "The version to be released"
        required: true

jobs:
  test_execution:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          #          - centos/8
          #          - centos/7
          #          - ol/7
          #          - debian/stretch
          #          - debian/buster
          #          - debian/bullseye
          #          - ubuntu/bionic
          - ubuntu/focal
    env:
      PLATFORM: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev libssl-dev python3-testresources

      - name: Install python requirements
        run: python -m pip install -r packaging_automation/requirements.txt

      - name: Citus package tests
        run: |
          python -m  packaging_automation.test_citus_package \
          --prj_ver 10.2.1 \
          --os_release ${{ matrix.platform }}
