name: Citus package tests

on:
  push:
    branches:
      - "**"

  workflow_dispatch:
    inputs:
      prj_ver:
        description: "The version to be released"
        default: 10.2.1
        required: true

jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      pg_versions: ${{ steps.generate-postgres.outputs.pg_versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev libssl-dev python3-testresources
      - name: Install python requirements
        run: python -m pip install -r packaging_automation/requirements.txt
      - name: generate postgres
        id: generate-postgres
        run: |
          POSTGRES_VERSIONS=$(python -m packaging_automation.get_postgres_versions --prj_ver 10.2.1)
          echo "Postgres Version: ${POSTGRES_VERSIONS}"
          echo "::set-output name=pg_versions::${POSTGRES_VERSIONS}"
  test_execution:
    runs-on: ubuntu-latest
    needs: metadata
    strategy:
      fail-fast: false
      matrix:
        platform:
          - centos/8
          - centos/7
          - ol/7
          - debian/stretch
          - debian/buster
          - debian/bullseye
          - ubuntu/bionic
          - ubuntu/focal
        pg: ${{ fromJson(needs.metadata.outputs.pg_versions) }}
    env:
      PLATFORM: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev libssl-dev python3-testresources

      - name: Install python requirements
        run: python -m pip install -r packaging_automation/requirements.txt

      - name: Citus package tests
        run: |
          export PROJECT_VERSION="${{ github.event.inputs.name }}"
          python -m  packaging_automation.test_citus_package \
          --prj_ver "${{ github.event.inputs.prj_ver }}" \
          --os_release ${{ matrix.platform }} \
          --pg_major_version ${{ matrix.pg }}
