name: citus-package-tests2

on:
  push:
    branches:
      - "**"

  workflow_dispatch:
    inputs:
      project_version:
        description: "The version to be tested"

jobs:
  test_execution:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - centos/8
          - centos/7
          - ol/7
          - debian/stretch
          - debian/buster
          - debian/bullseye
          - ubuntu/bionic
          - ubuntu/focal
        pg: [13,14]
    env:
      PLATFORM: ${{ matrix.platform }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev libssl-dev python3-testresources

      - name: Install python requirements
        run: python -m pip install -r packaging_automation/requirements.txt

      - name: Citus package tests
        run: |
          export PROJECT_VERSION="${{ github.event.inputs.project_version }}"
          echo "Citus Version: ${PROJECT_VERSION} "
          [ -z ${PROJECT_VERSION} ] && export PROJECT_VERSION=10.2.1
          python -m  packaging_automation.test_citus_package \
          --project_version 11.0.0_beta \
          --os_release ${{ matrix.platform }} \
          --pg_major_version ${{ matrix.pg }}
