name: Packaging helper methods tests

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

on:
  push:
    branches: "**"

  workflow_dispatch:

jobs:

  unit_test_execution:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2


      - name: Citus package tests
        run: python -m pytest -q packaging_automation/tests/test_citus_package_side_methods.py


