name: Docker image creation tests

on:
  push:
    branches: "**"

  workflow_dispatch:

jobs:

  unit_test_execution:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

     - name: Install package dependencies
        run: sudo apt install libcurl4-openssl-dev libssl-dev

      - name: Install python requirements
        run: python -m pip install -r packaging_automation/requirements.txt

      - name: Build and publish docker images tests
        run: python -m pytest -q packaging_automation/tests/test_publish_docker.py


