name: Statistics Schedule

env:
  JOB_NAME: ${{ matrix.GH_TOKEN }}

on:
  schedule:
    - cron:  '15 0 * * *'

  workflow_dispatch:

jobs:

  execute_job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job_name: [ docker_pull_citus ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install package dependencies
        run: sudo apt install libcurl4-openssl-dev libssl-dev

      - name: Install python requirements
        run: python -m pip install -r packaging_automation/requirements.txt

      - name: Execute 'Docker Pull for Citus Repo'
        run:


