name: Statistics Schedule

env:
  DB_USER_NAME: ${{ secrets.STATS_DB_USER_NAME }}
  DB_PASSWORD: ${{ secrets.STATS_DB_PASSWORD }}
  DB_HOST_AND_PORT: ${{ secrets.STATS_DB_HOST_AND_PORT }}
  DB_NAME: ${{ secrets.STATS_DB_NAME }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
on:
  schedule:
    - cron: "15 0 * * *"
  # Should be commented out when changing this file since pipelines with trigger type schedule
  # could not be tested on non-main branch
  #  push:
  #    branches: "**"

  workflow_dispatch:

jobs:
  execute_job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job_name: [docker_pull_citus, github_clone_citus]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install package dependencies
        run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev libssl-dev

      - name: Install python requirements
        run: python -m pip install -r packaging_automation/requirements.txt

      - name: Execute 'Docker Pull for Citus Repo'
        run: packaging_automation/bash/daily-statistics-job.sh
        env:
          JOB_NAME: ${{ matrix.JOB_NAME }}
