name: Statistics Tests

env:
  DB_USER_NAME: ${{ secrets.STATS_DB_USER_NAME }}
  DB_PASSWORD: ${{ secrets.STATS_DB_PASSWORD }}
  DB_HOST_AND_PORT: ${{ secrets.STATS_DB_HOST_AND_PORT }}
  DB_NAME: ${{ secrets.STATS_DB_NAME }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  PACKAGE_CLOUD_API_TOKEN: ${{ secrets.PACKAGE_CLOUD_API_TOKEN }}
  PACKAGE_CLOUD_ADMIN_API_TOKEN: ${{ secrets.PACKAGE_CLOUD_ADMIN_API_TOKEN }}
on:
  push:
    branches:
      - "statistics/**"
      - "dependabot/**"

  workflow_dispatch:

jobs:
  unit_test_execution:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install package dependencies
        run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev libssl-dev python3-testresources

      - name: Install python requirements
        run: python -m pip install -r packaging_automation/requirements.txt

      - name: Unit tests for "Docker statistics"
        run: python -m pytest -q packaging_automation/tests/test_docker_statistics_collector.py

      - name: Unit tests for "Github clone statistics"
        run: python -m pytest -q packaging_automation/tests/test_github_statistics_collector.py

      - name: Unit tests for "Packagecloud download statistics"
        run: python -m pytest -q packaging_automation/tests/test_package_cloud_statistics_collector.py

      - name: Unit tests for "Homebrew download statistics"
        run: python -m pytest -q packaging_automation/tests/test_homebrew_statistics_collector.py
