name: Statistics Schedule

env:
  DB_USER_NAME: ${{ secrets.STATS_DB_USER_NAME }}
  DB_PASSWORD: ${{ secrets.STATS_DB_PASSWORD }}
  DB_HOST_AND_PORT: ${{ secrets.STATS_DB_HOST_AND_PORT }}
  DB_NAME: ${{ secrets.STATS_DB_NAME }}
on:
  schedule:
    - cron: "0 16 * * *"
  push:
    branches:
      - "statistics/**"
      - "dependabot/**"

  workflow_dispatch:

jobs:
  execute_job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        job_name: [docker_pull_citus, github_clone_citus, homebrew_citus]

    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.GH_APP_ID || secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_KEY }}
          owner: citusdata

      - name: Export GitHub App token to environment
        run: echo "GH_TOKEN=${{ steps.app-token.outputs.token }}" >> "$GITHUB_ENV"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install package dependencies
        run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev libssl-dev python3-testresources

      - name: Install python requirements
        run: python -m pip install -r packaging_automation/requirements.txt

      - name: Execute 'Fetch Daily Statistics'
        run: packaging_automation/bash/daily-statistics-job.sh
        env:
          JOB_NAME: "${{ matrix.JOB_NAME }}"
