name: Tool Tests

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  MICROSOFT_EMAIL: gindibay@microsoft.com
  USER_NAME: Gurkan Indibay
  MAIN_BRANCH: all-citus

on:
  push:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  make-install:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Install all scripts
        run: make && sudo make install

  unit_test_execution:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Define git credentials
        run: git config --global user.email "${MICROSOFT_EMAIL}"&& git config --global user.name "${USER_NAME}"

      - name: Install package dependencies
        run: sudo apt-get update && sudo apt-get install libcurl4-openssl-dev libssl-dev

      - name: Install python requirements
        run: python -m pip install -r packaging_automation/requirements.txt

      - name: Run static code analysis
        run: python -m prospector

      - name: Unit tests for "Common tools"
        run: python -m pytest -q packaging_automation/tests/test_common_tool_methods.py

      - name: Unit tests for "Update Package Properties"
        run: python -m pytest -q packaging_automation/tests/test_update_package_properties.py

      - name: Unit tests for "Prepare Release"
        run: python -m pytest -q packaging_automation/tests/test_prepare_release.py

      - name: Unit tests for "Update Docker"
        run: python -m pytest -q packaging_automation/tests/test_update_docker.py

      - name: Unit tests for "Update Pgxn"
        run: python -m pytest -q packaging_automation/tests/test_update_pgxn.py

      - name: Packaging Warning Handler
        run: python -m pytest -q packaging_automation/tests/test_packaging_warning_handler.py
