name: Tool Tests

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

on:
  push:
    branches: "**"

  workflow_dispatch:

jobs:
  unit_test_execution:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: sudo apt install libcurl4-openssl-dev libssl-dev

      - name: Define git credentails
        run: git config --global user.email "gindibay@microsoft.com"&& git config --global user.name "Gurkan Indibay"

      - name: install requirements
        run: python -m pip install -r packaging_automation/requirements.txt

      - name: Unit tests for "Update Package Properties"
        run:  python -m pytest -q packaging_automation/tests/test_update_package_properties.py

      - name: Unit tests for "Prepare Release"
        run: python -m pytest -q packaging_automation/tests/test_prepare_release.py

      - name: Unit tests for "Update Docker"
        run: python -m pytest -q packaging_automation/tests/test_update_docker.py

      - name: Unit tests for "Update Pgxn"
        run: python -m pytest -q packaging_automation/tests/test_update_pgxn.py

      - name: Citus Package Tests
        run: python -m pytest -q packaging_automation/tests/test_citus_package_side_methods.py

      - name: Packaging Warning Handler
        run: python -m pytest -q packaging_automation/tests/packaging_warning_handler.py


