name: Tool Tests

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Define git credentails
        run: git config --global user.email "gindibay@microsoft.com"&& git config --global user.name "Gurkan Indibay"
      - name: install requirements
        run: python -m pip install -r python/requirements.txt
      - name: Unit tests for "Update Package Properties"
        run: python -m unittest $(pwd)/python/tests/test_update_package_properties.py
      - name: Unit tests for "Prepare Release"
        run: python -m unittest $(pwd)/python/tests/test_prepare_release.py


   
