name: Tool Tests

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

on:
  push:
    branches: "**"

  workflow_dispatch:

jobs:
  unit_test_execution:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: intall dependencies
        run: sudo apt install libcurl4-openssl-dev libssl-dev
      - name: install requirements
        run: python -m pip install -r python/requirements.txt
      - name: Execute Unit tests
        run: python -m unittest python/tests/test_update_package_properties.py
